version: "3"

services:
  flaskapp:
    build: .
    restart: unless-stopped
    image: marianferenc/flask-app:0.1
    command: python3 main.py -debugMode=True
    ports: ['8080:8080']
    volumes: ['./src:/flask_project']
